import { Suspense } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import Catalog from '@/components/Catalog';
export default function Home() { return <>
<section className="hero"><div className="container heroGrid"><div className="heroCopy"><span className="eyebrow">VERIFIED • FLEXIBLE • ON-DEMAND</span><h1>Your trusted Buddy for everyday help.</h1><p>Book verified student Buddies for household support, errands and everyday assistance — now, later, or every month.</p><div className="ctaRow"><Link className="primaryButton" href="/book">Book Now</Link><Link className="secondaryButton" href="/book?type=prebooked">Pre-Book</Link><Link className="ghostButton" href="/book?type=monthly_session">Monthly Package</Link></div><div className="trustRow"><span>✓ Verified profiles</span><span>✓ Secure payments</span><span>✓ Live support</span></div></div><div className="heroVisual"><div className="heroBlob"></div><Image src="/assets/welcome-hero.png" alt="Hepki service" width={620} height={620} priority /></div></div></section>
<section className="section"><div className="container"><div className="sectionHeading"><span className="eyebrow">HOW IT WORKS</span><h2>Help in three simple steps</h2></div><div className="stepsGrid"><div><b>01</b><h3>Choose Service</h3><p>Pick the category and booking type that suits you.</p></div><div><b>02</b><h3>Book a Buddy</h3><p>Select a slot and address. We’ll match you with an available Buddy.</p></div><div><b>03</b><h3>Task Done</h3><p>Pay securely, track status and rate your experience.</p></div></div></div></section>
<section className="section soft"><div className="container"><div className="sectionHeading split"><div><span className="eyebrow">POPULAR SERVICES</span><h2>Top categories</h2></div><Link href="/categories">View all categories →</Link></div><Suspense fallback={<p role="status">Loading services…</p>}><Catalog limit={4}/></Suspense></div></section>
<section className="section"><div className="container trustPanel"><div><span className="eyebrow">SAFETY FIRST</span><h2>Book with confidence.</h2><p>Verified Buddies, clear booking status, secure payments and safety-first workflows are built into the Hepki experience.</p><Link className="primaryButton" href="/safety">Explore Safety & Trust</Link></div><div className="trustStats"><div><strong>24/7</strong><span>Support ready</span></div><div><strong>100%</strong><span>Verified profiles</span></div><div><strong>Secure</strong><span>Razorpay payments</span></div></div></div></section>
<section className="section appBand"><div className="container appBandInner"><div><span className="eyebrow light">TAKE HEPKI WITH YOU</span><h2>Book faster from the app.</h2><p>Continue your experience on Android and iOS with live booking updates and notifications.</p></div><div className="storeButtons"><button>Download on App Store</button><button>Get it on Google Play</button></div></div></section>
</> }
