import { Suspense } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import Catalog from '@/components/Catalog';
export default function Home() { return <>
<section className="hero"><div className="container heroGrid"><div className="heroCopy"><span className="eyebrow">VERIFIED • FLEXIBLE • ON-DEMAND</span><h1>Your trusted Buddy for everyday help.</h1><p>Book verified student Buddies for household support, errands and everyday assistance — now, later, or every month.</p><div className="ctaRow"><Link className="primaryButton" href="/book">Book Now</Link><Link className="secondaryButton" href="/book?type=prebooked">Pre-Book</Link><Link className="packageButton" href="/book?type=monthly_session"><span className="pkgIcon" aria-hidden="true"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/></svg></span><span>Monthly Package</span><span className="pkgBadge">Save 20%</span></Link></div><div className="trustRow"><span>✓ Verified profiles</span><span>✓ Secure payments</span><span>✓ Live support</span></div></div><div className="heroVisual"><div className="heroBlob"></div><Image src="/assets/welcome-hero.png" alt="Hepki service" width={620} height={620} priority /></div></div></section>
<section className="section howItWorksSection"><div className="container"><div className="sectionHeading centered"><span className="eyebrow">HOW IT WORKS</span><h2>Help in three simple steps</h2><p>Getting reliable, trusted help shouldn't be complicated. Here is how easy it is to book a Buddy today.</p></div><div className="stepsGrid"><Link href="/categories" className="stepCard"><div className="stepTop"><span className="stepBadge">Step 01</span><span className="stepIcon" aria-hidden="true"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/></svg></span></div><div className="stepContent"><h3>Choose Service</h3><p>Pick the category and booking type that suits you — on-demand, pre-booked, or monthly.</p></div><div className="stepMeta"><span>Explore 10+ categories</span><span className="stepArrow">→</span></div></Link><Link href="/book" className="stepCard"><div className="stepTop"><span className="stepBadge">Step 02</span><span className="stepIcon" aria-hidden="true"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg></span></div><div className="stepContent"><h3>Book a Buddy</h3><p>Select your preferred slot and address. We’ll instantly match you with a verified, background-checked Buddy.</p></div><div className="stepMeta"><span>Instant verification</span><span className="stepArrow">→</span></div></Link><Link href="/safety" className="stepCard"><div className="stepTop"><span className="stepBadge">Step 03</span><span className="stepIcon" aria-hidden="true"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg></span></div><div className="stepContent"><h3>Task Done</h3><p>Pay securely via Razorpay, track live status, and leave your rating with complete peace of mind.</p></div><div className="stepMeta"><span>Safe & cashless</span><span className="stepCheck">✓</span></div></Link></div></div></section>
<section className="section soft"><div className="container"><div className="sectionHeading split"><div><span className="eyebrow">POPULAR SERVICES</span><h2>Top categories</h2></div><Link href="/categories">View all categories →</Link></div><Suspense fallback={<p role="status">Loading services…</p>}><Catalog limit={4}/></Suspense></div></section>
<section className="section"><div className="container trustPanel"><div><span className="eyebrow">SAFETY FIRST</span><h2>Book with confidence.</h2><p>Verified Buddies, clear booking status, secure payments and safety-first workflows are built into the Hepki experience.</p><Link className="primaryButton" href="/safety">Explore Safety & Trust</Link></div><div className="trustStats"><div><strong>24/7</strong><span>Support ready</span></div><div><strong>100%</strong><span>Verified profiles</span></div><div><strong>Secure</strong><span>Razorpay payments</span></div></div></div></section>
<section className="section appBand"><div className="container appBandInner"><div><span className="eyebrow light">TAKE HEPKI WITH YOU</span><h2>Book faster from the app.</h2><p>Continue your experience on Android and iOS with live booking updates and notifications.</p></div><div className="storeButtons"><button>Download on App Store</button><button>Get it on Google Play</button></div></div></section>
</> }
